"""
Django settings for OSSE project.

Generated by 'django-admin startproject' using Django 2.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@yvo5va0sb6-i@t+vw3tr3b=)^^uh-9#0$*qs%8kxtwe7544-m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'se',
    'django.contrib.admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'osse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'osse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'django',
        'USER': 'django',
        'PASSWORD': 'password',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/html/static'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGE_CODE = 'fr-FR'
USE_L10N = False
DATETIME_FORMAT = 'd/m/y H:i'
TIME_ZONE = 'Europe/Paris'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'crawler': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

OSSE_DEFAULT_PAGE_SIZE = 20
OSSE_MAX_PAGE_SIZE = 200

OSSE_LANGDETECT_TO_POSTGRES = {
    'ar': {
        'name': 'arabic',
        'flag': 'العربية'
    },
    'da': {
        'name': 'danish',
        'flag': '🇩🇰'
    },
    'nl': {
        'name': 'dutch',
        'flag': '🇳🇱'
    },
    'en': {
        'name': 'english',
        'flag': '🇬🇧'
    },
    'fi': {
        'name': 'finnish',
        'flag': '🇫🇮'
    },
    'fr': {
        'name': 'french',
        'flag': '🇫🇷'
    },
    'de': {
        'name': 'german',
        'flag': '🇩🇪'
    },
    'el': {
        'name': 'greek',
        'flag': '🇬🇷'
    },
    'hu': {
        'name': 'hungarian',
        'flag': '🇭🇺'
    },
    'id': {
        'name': 'indonesian',
        'flag': '🇮🇩'
    },
    'ga': {
        'name': 'irish',
        'flag': '🇮🇪'
    },
    'it': {
        'name': 'italian',
        'flag': '🇮🇹'
    },
    'lt': {
        'name': 'lithuanian',
        'flag': '🇱🇹'
    },
    'ne': {
        'name': 'nepali',
        'flag': '🇳🇵'
    },
    'no': {
        'name': 'norwegian',
        'flag': '🇳🇴'
    },
    'pt': {
        'name': 'portuguese',
        'flag': '🇵🇹'
    },
    'ro': {
        'name': 'romanian',
        'flag': '🇷🇴'
    },
    'ru': {
        'name': 'russian',
        'flag': '🇷🇺'
    },
    'es': {
        'name': 'spanish',
        'flag': '🇪🇸'
    },
    'sv': {
        'name': 'swedish',
        'flag': '🇸🇪'
    },
    'ta': {
        'name': 'tamil',
        'flag': 'தமிழ்'
    },
    'tr': {
        'name': 'turkish',
        'flag': '🇹🇷'
    },

    # Not supported by Postgres, but support by langdetect
    'af': {
        'name': 'afrikaans',
    },
    'bg': {
        'name': 'bulgarian',
        'flag': '🇧🇬'
    },
    'bn': {
        'name': 'bengali',
        'flag': '🇧🇩'
    },
    'ca': {
        'name': 'catalan'
    },
    'cs': {
        'name': 'czech',
        'flag': '🇨🇿'
    },
    'cy': {
        'name': 'welsh',
        'flag': '🏴󠁧󠁢󠁷󠁬󠁳󠁿'
    },
    'et': {
        'name': 'estonian',
        'flag': '🇪🇪'
    },
    'fa': {
        'name': 'persian',
        'flag': '🇮🇷'
    },
    'gu': {
        'name': 'gujarati',
        'flag': '🇮🇳'
    },
    'he': {
        'name': 'hebrew',
        'flag': '🇮🇱'
    },
    'hi': {
        'name': 'hindi',
        'flag': '🇮🇳'
    },
    'hr': {
        'name': 'croatian',
        'flag': '🇭🇷'
    },
    'ja': {
        'name': 'japanese',
        'flag': '🇯🇵'
    },
    'kn': {
        'name': 'kannada',
        'flag': '🇮🇳'
    },
    'ko': {
        'name': 'korean',
        'flag': '🇰🇷'
    },
    'lt': {
        'name': 'lithuanian',
        'flag': '🇱🇹'
    },
    'lv': {
        'name': 'latvian',
        'flag': '🇱🇻'
    },
    'mk': {
        'name': 'macedonian',
        'flag': '🇲🇰'
    },
    'ml': {
        'name': 'malayalam',
        'flag': '🇮🇳'
    },
    'mr': {
        'name': 'marathi',
        'flag': '🇮🇳'
    },
    'pa': {
        'name': 'punjabi',
        'flag': '🇵🇰'
    },
    'pl': {
        'name': 'polish',
        'flag': '🇵🇱'
    },
    'sk': {
        'name': 'slovak',
        'flag': '🇸🇰   '
    },
    'sl': {
        'name': 'slovenian',
        'flag': '🇸🇮'
    },
    'so': {
        'name': 'shona',
        'flag': '🇿🇼'
    },
    'sq': {
        'name': 'albanian',
        'flag': '🇦🇱'
    },
    'sw': {
        'name': 'swahili'
    },
    'te': {
        'name': 'telugu',
        'flag': '🇮🇳'
    },
    'th': {
        'name': 'thai',
        'flag': '🇹🇭'
    },
    'tl': {
        'name': 'tagalog',
        'flag': '🇵🇭'
    },
    'uk': {
        'name': 'ukrainian',
        'flag': '🇺🇦'
    },
    'ur': {
        'name': 'urdu'
    },
    'vi': {
        'name': 'vietnamese',
        'flag': '🇻🇳'
    },
    'zh-cn': {
        'name': 'chinese',
        'flag': '🇨🇳'
    },
    'zh-tw': {
        'name': 'chinese',
        'flag': '🇹🇼'
    }
}
OSSE_FAIL_OVER_LANG = 'english'

from hashlib import md5
HASHING_ALGO = md5

USER_AGENT = 'OSSE'

# Exclude pages not yet indexed from search results
OSSE_EXCLUDE_NOT_INDEXED = True

# Exclude pages that redirect to an other from results
OSSE_EXCLUDE_REDIRECT = True
