# Copyright 2022-2023 Laurent Defert
#
#  This file is part of SOSSE.
#
# SOSSE is free software: you can redistribute it and/or modify it under the terms of the GNU Affero
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# SOSSE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along with SOSSE.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.2.19 on 2023-07-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se', '0003_sosse_1_1_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlpolicy',
            name='remove_nav_elements',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', help_text='Remove navigation related elements', max_length=4),
        ),
    ]
