# Copyright 2022-2023 Laurent Defert
#
#  This file is part of SOSSE.
#
# SOSSE is free software: you can redistribute it and/or modify it under the terms of the GNU Affero
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# SOSSE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along with SOSSE.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.2.19 on 2023-08-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se', '0006_sosse_1_4_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlpolicy',
            name='auth_login_url_re',
            field=models.TextField(blank=True, help_text='A redirection to an URL matching the regexp will trigger authentication', null=True, verbose_name='Login URL regexp'),
        ),
    ]
