# Copyright 2022-2024 Laurent Defert
#
#  This file is part of SOSSE.
#
# SOSSE is free software: you can redistribute it and/or modify it under the terms of the GNU Affero
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# SOSSE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along with SOSSE.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.2.19 on 2024-06-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('se', '0011_sosse_1_9_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlpolicy',
            name='hide_documents',
            field=models.BooleanField(default=False, help_text='Hide documents from search results'),
        ),
        migrations.AddField(
            model_name='document',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide this document from search results'),
        ),
        migrations.AddField(
            model_name='crawlpolicy',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
