# Copyright 2022-2024 Laurent Defert
#
#  This file is part of SOSSE.
#
# SOSSE is free software: you can redistribute it and/or modify it under the terms of the GNU Affero
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# SOSSE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along with SOSSE.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.2.19 on 2024-08-07 14:50

from django.db import migrations, models


def migrate_thumbnail(apps, schema_editor):
    CrawlPolicy = apps.get_model('se', 'CrawlPolicy')
    CrawlPolicy.objects.filter(create_thumbnails=False).update(thumbnail_mode='none')


def reverse_thumbnail(apps, schema_editor):
    CrawlPolicy = apps.get_model('se', 'CrawlPolicy')
    CrawlPolicy.objects.filter(thumbnail_mode='none').update(create_thumbnails=False)


class Migration(migrations.Migration):

    dependencies = [
        ('se', '0012_sosse_1_10_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlpolicy',
            name='thumbnail_mode',
            field=models.CharField(choices=[('preview', 'Page preview from metadata'), ('prevscreen', 'Preview from meta, screenshot as fallback'), ('screenshot', 'Take a screenshot'), ('none', 'No thumbnail')], default='prevscreen', help_text='Save thumbnails to display in search results', max_length=10),
        ),
        migrations.RunPython(migrate_thumbnail, reverse_thumbnail),
        migrations.RemoveField(
            model_name='crawlpolicy',
            name='create_thumbnails',
        ),
    ]
