# Copyright 2025 Laurent Defert
#
#  This file is part of SOSSE.
#
# SOSSE is free software: you can redistribute it and/or modify it under the terms of the GNU Affero
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# SOSSE is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along with SOSSE.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 3.2.19 on 2025-02-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("se", "0014_sosse_1_12_0"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlpolicy",
            name="hash_mode",
            field=models.CharField(
                choices=[("raw", "Raw content"), ("no_numbers", "Normalize numbers")],
                default="no_numbers",
                help_text="Content to check for modifications",
                max_length=10,
                verbose_name="Change detection",
            ),
        ),
        migrations.RenameField(
            model_name="crawlpolicy",
            old_name="recrawl_mode",
            new_name="recrawl_freq",
        ),
        migrations.AddField(
            model_name="crawlpolicy",
            name="recrawl_condition",
            field=models.CharField(
                choices=[("change", "On change only"), ("always", "Always"), ("manual", "On change or manual trigger")],
                default="change",
                help_text="Specifies the conditions under which a page is reprocessed",
                max_length=10,
                verbose_name="Condition",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="manual_crawl",
            field=models.BooleanField(default=False),
        ),
    ]
