# Copyright 2025 Laurent Defert
#
#  This file is part of Sosse.
#
# Sosse is free software: you can redistribute it and/or modify it under the terms of the GNU Affero
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Sosse is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along with Sosse.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 4.2.23 on 2025-10-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("se", "0024_add_queue_to_collection_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="queue_to_any_collection",
            field=models.BooleanField(
                default=False,
                help_text="When a URL doesn't match this Collection's regex patterns, check all Collections and queue it in the first matching one.",
                verbose_name="Queue links to any collection",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="queue_to_collections",
            field=models.ManyToManyField(
                blank=True,
                help_text="When a URL doesn't match this Collection's regex patterns, check only these Collections and queue it there.",
                to="se.collection",
                verbose_name="Queue links to specific collections",
            ),
        ),
    ]
