FROM debian:bullseye
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y git python3-pip python3-dev python3-virtualenv python3-venv build-essential postgresql libpq-dev libmagic1 nginx chromium chromium-driver uwsgi uwsgi-plugin-python3
